# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #To use triggers you need install vagrant-triggers plugin installed
  config.trigger.before :up,:vm => "centosAm" do
    info "Copying insecure vagrant ssh key to current directory"
    run "cp /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/keys/vagrant ./vagrant-insecure-key"
    run "cp /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/keys/vagrant.pub ./vagrant-insecure-key.pub"
    run "chmod 400 ./vagrant-insecure-key"    
  end

  #Don't update information about 
  config.vm.box_check_update = false

  #Don't generate the new ssh keys for vagrant boxes - vagrant insecure will be used instead
  config.ssh.insert_key = false

  config.vm.define :dck1 do |dck1_config|
    dck1_config.vm.box = "centos/7"
    dck1_config.vm.synced_folder "./sources", "/vagrant" , type: "rsync", rsync__exclude: ".git/" #, disabled: true
    dck1_config.vm.hostname = "dck1"
    dck1_config.vm.network "private_network", ip: "10.0.15.50"
    dck1_config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.linked_clone = true
    end

    dck1_config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./provision-dockers.yml"
      ansible.config_file = "./ansible.cfg"
      ansible.inventory_path = "./hosts.ini"
      ansible.limit = "dockers"
   end

  end

end

