---
- hosts: main
  become: yes
  become_user: root

  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - vagrant

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

